import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import getCurrentUser from "@/actions/getCurrentUser";
import { User } from "@prisma/client";
import ModelProvider from "@/components/providers/ModelProvider";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: User | null = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}> 
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
          >
            <ModelProvider />
      <Suspense>
            <Toaster />
            <div className="flex flex-row justify-center items-start w-full">
              <div className="flex-[0.2] w-full hidden flex-col justify-start items-start md:flex">
                <Sidebar currentUser={user} mobile={false} />
              </div>
              <div className="flex flex-col justify-center items-center flex-1 md:flex-[0.8] w-full">
                   <Navbar currentUser={user} />
                   {children}
              </div>
            </div>
      </Suspense>
          </ThemeProvider>
        </body>
    </html>
  );
}
